config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Legacy API Routes
  match "/api/v1/send/message" => "legacy_api/send#message", via: [:get, :post, :patch, :put]
  match "/api/v1/send/raw" => "legacy_api/send#raw", via: [:get, :post, :patch, :put]
  match "/api/v1/messages/message" => "legacy_api/messages#message", via: [:get, :post, :patch, :put]
  match "/api/v1/messages/deliveries" => "legacy_api/messages#deliveries", via: [:get, :post, :patch, :put]

  scope "org/:org_permalink", as: "organization" do
    resources :domains, only: [:index, :new, :create, :destroy] do
      match :verify, on: :member, via: [:get, :post]
      get :setup, on: :member
      post :check, on: :member
    end
    resources :servers, except: [:index] do
      resources :domains, only: [:index, :new, :create, :destroy] do
        match :verify, on: :member, via: [:get, :post]
        get :setup, on: :member
        post :check, on: :member
      end
      resources :track_domains do
        post :toggle_ssl, on: :member
        post :check, on: :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, on: :collection
        get :outgoing, on: :collection
        get :held, on: :collection
        get :activity, on: :member
        get :plain, on: :member
        get :html, on: :member
        get :html_raw, on: :member
        get :attachments, on: :member
        get :headers, on: :member
        get :attachment, on: :member
        get :download, on: :member
        get :spam_checks, on: :member
        post :retry, on: :member
        post :cancel_hold, on: :member
        get :suppressions, on: :collection
        delete :remove_from_queue, on: :member
        get :deliveries, on: :member
      end
      resources :webhooks do
        get :history, on: :collection
        get "history/:uuid", on: :collection, action: "history_request", as: "history_request"
      end
      get :limits, on: :member
      get :retention, on: :member
      get :queue, on: :member
      get :spam, on: :member
      get :delete, on: :member
      get "help/outgoing" => "help#outgoing"
      get "help/incoming" => "help#incoming"
      get :advanced, on: :member
      post :suspend, on: :member
      post :unsuspend, on: :member
    end

    resources :ip_pool_rules
    resources :ip_pools, controller: "organization_ip_pools" do
      put :assignments, on: :collection
    end
    root "servers#index"
    get "settings" => "organizations#edit"
    patch "settings" => "organizations#update"
    get "delete" => "organizations#delete"
    delete "delete" => "organizations#destroy"
  end

  resources :organizations, except: [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get "settings" => "user#edit"
  patch "settings" => "user#update"
  post "persist" => "sessions#persist"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  match "login/reset" => "sessions#begin_password_reset", :via => [:get, :post]
  match "login/reset/:token" => "sessions#finish_password_reset", :via => [:get, :post]

  if Postal::Config.oidc.enabled?
    get "auth/oidc/callback", to: "sessions#create_from_oidc"
  end

  get ".well-known/jwks.json" => "well_known#jwks"

  get "ip" => "sessions#ip"

  root "organizations#index"
end

app/models/domain.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: domains
#
#  id                     :integer          not null, primary key
#  server_id              :integer
#  uuid                   :string(255)
#  name                   :string(255)
#  verification_token     :string(255)
#  verification_method    :string(255)
#  verified_at            :datetime
#  dkim_private_key       :text(65535)
#  created_at             :datetime
#  updated_at             :datetime
#  dns_checked_at         :datetime
#  spf_status             :string(255)
#  spf_error              :string(255)
#  dkim_status            :string(255)
#  dkim_error             :string(255)
#  mx_status              :string(255)
#  mx_error               :string(255)
#  return_path_status     :string(255)
#  return_path_error      :string(255)
#  outgoing               :boolean          default(TRUE)
#  incoming               :boolean          default(TRUE)
#  owner_type             :string(255)
#  owner_id               :integer
#  dkim_identifier_string :string(255)
#  use_for_any            :boolean
#
# Indexes
#
#  index_domains_on_server_id  (server_id)
#  index_domains_on_uuid       (uuid)
#

require "resolv"

class Domain < ApplicationRecord

  include HasUUID

  include HasDNSChecks

  VERIFICATION_EMAIL_ALIASES = %w[webmaster postmaster admin administrator hostmaster].freeze
  VERIFICATION_METHODS = %w[DNS Email].freeze

  belongs_to :server, optional: true
  belongs_to :owner, optional: true, polymorphic: true
  has_many :routes, dependent: :destroy
  has_many :track_domains, dependent: :destroy

  validates :name, presence: true, format: { with: /\A[a-z0-9\-.]*\z/ }, uniqueness: { case_sensitive: false, scope: [:owner_type, :owner_id], message: "is already added" }
  validates :verification_method, inclusion: { in: VERIFICATION_METHODS }

  random_string :dkim_identifier_string, type: :chars, length: 6, unique: true, upper_letters_only: true

  before_create :generate_dkim_key

  scope :verified, -> { where.not(verified_at: nil) }

  before_save :update_verification_token_on_method_change

  def verified?
    verified_at.present?
  end

  def mark_as_verified
    return false if verified?

    self.verified_at = Time.now
    save!
  end

  def parent_domains
    parts = name.split(".")
    parts[0, parts.size - 1].each_with_index.map do |_, i|
      parts[i..].join(".")
    end
  end

  def generate_dkim_key
    self.dkim_private_key = OpenSSL::PKey::RSA.new(1024).to_s
  end

  def dkim_key
    return nil unless dkim_private_key

    @dkim_key ||= OpenSSL::PKey::RSA.new(dkim_private_key)
  end

  def to_param
    uuid
  end

  def verification_email_addresses
    parent_domains.map do |domain|
      VERIFICATION_EMAIL_ALIASES.map do |a|
        "#{a}@#{domain}"
      end
    end.flatten
  end

  def spf_record
    "v=spf1 a mx include:#{Postal::Config.dns.spf_include} ~all"
  end

  def dkim_record
    return if dkim_key.nil?

    public_key = dkim_key.public_key.to_s.gsub(/-+[A-Z ]+-+\n/, "").gsub(/\n/, "")
    "v=DKIM1; t=s; h=sha256; p=#{public_key};"
  end

  def dkim_identifier
    return nil unless dkim_identifier_string

    Postal::Config.dns.dkim_identifier + "-#{dkim_identifier_string}"
  end

  def dkim_record_name
    identifier = dkim_identifier
    return if identifier.nil?

    "#{identifier}._domainkey"
  end

  def return_path_domain
    "#{Postal::Config.dns.custom_return_path_prefix}.#{name}"
  end

  # Returns a DNSResolver instance that can be used to perform DNS lookups needed for
  # the verification and DNS checking for this domain.
  #
  # @return [DNSResolver]
  def resolver
    return DNSResolver.local if Postal::Config.postal.use_local_ns_for_domain_verification?

    @resolver ||= DNSResolver.for_domain(name)
  end

  def dns_verification_string
    "#{Postal::Config.dns.domain_verify_prefix} #{verification_token}"
  end

  def verify_with_dns
    return false unless verification_method == "DNS"

    result = resolver.txt(name)

    if result.include?(dns_verification_string)
      self.verified_at = Time.now
      return save
    end

    false
  end

  private

  def update_verification_token_on_method_change
    return unless verification_method_changed?

    if verification_method == "DNS"
      self.verification_token = SecureRandom.alphanumeric(32)
    elsif verification_method == "Email"
      self.verification_token = rand(999_999).to_s.ljust(6, "0")
    else
      self.verification_token = nil
    end
  end

end

app/models/domain/dns_checks.rb
require "resolv"

class Domain

  def dns_ok?
    spf_status == "OK" && dkim_status == "OK" && ["OK", "Missing"].include?(mx_status) && ["OK", "Missing"].include?(return_path_status)
  end

  def dns_checked?
    spf_status.present?
  end

  def check_dns(source = :manual)
    check_spf_record
    check_dkim_record
    check_mx_records
    check_return_path_record
    self.dns_checked_at = Time.now
    save!
    if source == :auto && !dns_ok? && owner.is_a?(Server)
      WebhookRequest.trigger(owner, "DomainDNSError", {
        server: owner.webhook_hash,
        domain: name,
        uuid: uuid,
        dns_checked_at: dns_checked_at.to_f,
        spf_status: spf_status,
        spf_error: spf_error,
        dkim_status: dkim_status,
        dkim_error: dkim_error,
        mx_status: mx_status,
        mx_error: mx_error,
        return_path_status: return_path_status,
        return_path_error: return_path_error
      })
    end
    dns_ok?
  end

  #
  # SPF
  #

  def check_spf_record
    result = resolver.getresources(name, Resolv::DNS::Resource::IN::TXT)
    spf_records = result.map(&:data).select { |d| d =~ /\Av=spf1/ }
    if spf_records.empty?
      self.spf_status = "Missing"
      self.spf_error = "No SPF record exists for this domain"
    else
      suitable_spf_records = spf_records.select { |d| d =~ /include:\s*#{Regexp.escape(Postal.config.dns.spf_include)}/ }
      if suitable_spf_records.empty?
        self.spf_status = "Invalid"
        self.spf_error = "An SPF record exists but it doesn't include #{Postal.config.dns.spf_include}"
        false
      else
        self.spf_status = "OK"
        self.spf_error = nil
        true
      end
    end
  end

  def check_spf_record!
    check_spf_record
    save!
  end

  #
  # DKIM
  #

  def check_dkim_record
    domain = "#{dkim_record_name}.#{name}"
    result = resolver.getresources(domain, Resolv::DNS::Resource::IN::TXT)
    records = result.map(&:data)
    if records.empty?
      self.dkim_status = "Missing"
      self.dkim_error = "No TXT records were returned for #{domain}"
    else
      sanitised_dkim_record = records.first.strip.ends_with?(";") ? records.first.strip : "#{records.first.strip};"
      if records.size > 1
        self.dkim_status = "Invalid"
        self.dkim_error = "There are #{records.size} records for at #{domain}. There should only be one."
      elsif sanitised_dkim_record != dkim_record
        self.dkim_status = "Invalid"
        self.dkim_error = "The DKIM record at #{domain} does not match the record we have provided. Please check it has been copied correctly."
      else
        self.dkim_status = "OK"
        self.dkim_error = nil
        true
      end
    end
  end

  def check_dkim_record!
    check_dkim_record
    save!
  end

  #
  # MX
  #

  def check_mx_records
    result = resolver.getresources(name, Resolv::DNS::Resource::IN::MX)
    records = result.map(&:exchange)
    if records.empty?
      self.mx_status = "Missing"
      self.mx_error = "There are no MX records for #{name}"
    else
      missing_records = Postal.config.dns.mx_records.dup - records.map { |r| r.to_s.downcase }
      if missing_records.empty?
        self.mx_status = "OK"
        self.mx_error = nil
      elsif missing_records.size == Postal.config.dns.mx_records.size
        self.mx_status = "Missing"
        self.mx_error = "You have MX records but none of them point to us."
      else
        self.mx_status = "Invalid"
        self.mx_error = "MX #{missing_records.size == 1 ? 'record' : 'records'} for #{missing_records.to_sentence} are missing and are required."
      end
    end
  end

  def check_mx_records!
    check_mx_records
    save!
  end

  #
  # Return Path
  #

  def check_return_path_record
    result = resolver.getresources(return_path_domain, Resolv::DNS::Resource::IN::CNAME)
    records = result.map { |r| r.name.to_s.downcase }
    if records.empty?
      self.return_path_status = "Missing"
      self.return_path_error = "There is no return path record at #{return_path_domain}"
    elsif records.size == 1 && records.first == Postal.config.dns.return_path
      self.return_path_status = "OK"
      self.return_path_error = nil
    else
      self.return_path_status = "Invalid"
      self.return_path_error = "There is a CNAME record at #{return_path_domain} but it points to #{records.first} which is incorrect. It should point to #{Postal.config.dns.return_path}."
    end
  end

  def check_return_path_record!
    check_return_path_record
    save!
  end

end

# -*- SkipSchemaAnnotations

app/controllers/domains_controller.rb
# frozen_string_literal: true

class DomainsController < ApplicationController

  include WithinOrganization

  before_action do
    if params[:server_id]
      @server = organization.servers.present.find_by_permalink!(params[:server_id])
      params[:id] && @domain = @server.domains.find_by_uuid!(params[:id])
    else
      params[:id] && @domain = organization.domains.find_by_uuid!(params[:id])
    end
  end

  def index
    if @server
      @domains = @server.domains.order(:name).to_a
    else
      @domains = organization.domains.order(:name).to_a
    end
  end

  def new
    @domain = @server ? @server.domains.build : organization.domains.build
  end

  def create
    scope = @server ? @server.domains : organization.domains
    @domain = scope.build(params.require(:domain).permit(:name, :verification_method))

    if current_user.admin?
      @domain.verification_method = "DNS"
      @domain.verified_at = Time.now
    end

    if @domain.save
      if @domain.verified?
        redirect_to_with_json [:setup, organization, @server, @domain]
      else
        redirect_to_with_json [:verify, organization, @server, @domain]
      end
    else
      render_form_errors "new", @domain
    end
  end

  def destroy
    @domain.destroy
    redirect_to_with_json [organization, @server, :domains]
  end

  def verify
    if @domain.verified?
      redirect_to [organization, @server, :domains], alert: "#{@domain.name} has already been verified."
      return
    end

    return unless request.post?

    case @domain.verification_method
    when "DNS"
      if @domain.verify_with_dns
        redirect_to_with_json [:setup, organization, @server, @domain], notice: "#{@domain.name} has been verified successfully. You now need to configure your DNS records."
      else
        respond_to do |wants|
          wants.html { flash.now[:alert] = "We couldn't verify your domain. Please double check you've added the TXT record correctly." }
          wants.json { render json: { flash: { alert: "We couldn't verify your domain. Please double check you've added the TXT record correctly." } } }
        end
      end
    when "Email"
      if params[:code]
        if @domain.verification_token == params[:code].to_s.strip
          @domain.mark_as_verified
          redirect_to_with_json [:setup, organization, @server, @domain], notice: "#{@domain.name} has been verified successfully. You now need to configure your DNS records."
        else
          respond_to do |wants|
            wants.html { flash.now[:alert] = "Invalid verification code. Please check and try again." }
            wants.json { render json: { flash: { alert: "Invalid verification code. Please check and try again." } } }
          end
        end
      elsif params[:email_address].present?
        raise Postal::Error, "Invalid email address" unless @domain.verification_email_addresses.include?(params[:email_address])

        AppMailer.verify_domain(@domain, params[:email_address], current_user).deliver
        if @domain.owner.is_a?(Server)
          redirect_to_with_json verify_organization_server_domain_path(organization, @server, @domain, email_address: params[:email_address])
        else
          redirect_to_with_json verify_organization_domain_path(organization, @domain, email_address: params[:email_address])
        end
      end
    end
  end

  def setup
    return if @domain.verified?

    redirect_to [:verify, organization, @server, @domain], alert: "You can't set up DNS for this domain until it has been verified."
  end

  def check
    if @domain.check_dns(:manual)
      redirect_to_with_json [organization, @server, :domains], notice: "Your DNS records for #{@domain.name} look good!"
    else
      redirect_to_with_json [:setup, organization, @server, @domain], alert: "There seems to be something wrong with your DNS records. Check below for information."
    end
  end

end

app/views/domains/_nav.html.haml
.navBar.navBar--secondary
  %ul
    %li.navBar__item= link_to "Domains", organization_server_domains_path(organization, @server), :class => ['navBar__link', active_nav == :domains ? 'is-active' : '']
    %li.navBar__item= link_to "Tracking Domains", organization_server_track_domains_path(organization, @server), :class => ['navBar__link', active_nav == :track_domains ? 'is-active' : '']

app/views/domains/_verify_with_dns.html.haml
%p.pageContent__intro.u-margin
  To verify your ownership of <b>#{@domain.name}</b>, you need to add a TXT record to this domain.
  The TXT record should point to the domain and include the value shown below.

%pre.codeBlock.u-margin= @domain.dns_verification_string

%p.pageContent__intro.u-margin
  Once you've added this, click the button below to verify the presence of this record and
  verify your domain.

.buttonSet
  = link_to "Verify TXT record", [:verify, organization, @server, @domain], :remote => true, :method => :post, :class => "button"
  = link_to "Back to domain list", [organization, @server, :domains], :class => "button button--neutral"

app/views/domains/_verify_with_email.html.haml
- if params[:email_address]
  %p.pageContent__intro.u-margin
    We've sent an email to <b>#{params[:email_address]}</b>. Please check your e-mail and enter
    the code you've been sent in the box below.
  = form_tag request.fullpath, :remote => true do
    = hidden_field_tag 'email_address', params[:email_address]
    %p.u-margin
      = text_field_tag "code", params[:code], :autofocus => true, :class => 'input input--text js-multibox'
    .buttonSet
      = submit_tag "Verify this domain", :class => 'button js-form-submit'
      = link_to "Back to domain list", [organization, @server, :domains], :class => "button button--neutral"


- else
  %p.pageContent__intro.u-margin
    To verify your ownership of <b>#{@domain.name}</b> by e-mail, choose an e-mail address from the list
    below. We'll then send you an email with a code which you'll need to enter below.

  = form_tag request.fullpath, :remote => true do
    %p.u-margin
      = select_tag "email_address", options_for_select(@domain.verification_email_addresses), :class => 'input input--select', :autofocus => true
    %p.buttonSet
      = submit_tag "Continue", :class => 'button'
      = link_to "Back to domain list", [organization, @server, :domains], :class => "button button--neutral"

app/views/domains/index.html.haml
- if @server
  - page_title << @server.name
- page_title << "Domains"

- if @server
  = render 'servers/sidebar', :active_server => @server
  = render 'servers/header', :active_nav => :domains
  = render 'nav', :active_nav => :domains
- else
  .pageHeader
    %h1.pageHeader__title
      %span.pageHeader__titlePrevious
        = @organization.name
        &rarr;
      Domains
  = render 'organizations/nav', :active_nav => :domains

.pageContent.pageContent--compact

  - if @domains.empty?
    .noData.noData--clean
      %h2.noData__title There are no domains for this server.
      %p.noData__text
        To send & receive messages you need to add & verify the domain you wish to send/receive
        messages to/from. Add your domain below to get started.
      %p.noData__button= link_to "Add your first domain", [:new, organization, @server, :domain], :class => "button button--positive"

  - else
    %ul.domainList.u-margin
      - for domain in @domains
        %li.domainList__item
          .domainList__details
            %p.domainList__name
              = link_to domain.name, [:setup, organization, @server, domain]
              - if domain.use_for_any?
                %span.label.label--blue Any
            %ul.domainList__checks
              - if domain.spf_status == 'OK'
                %li.domainList__check.domainList__check--ok SPF
              - elsif domain.spf_status.nil?
              - else
                %li.domainList__check.domainList__check--warning{:title => domain.spf_error}= link_to "SPF", [:setup, organization, @server, domain]

              - if domain.dkim_status == 'OK'
                %li.domainList__check.domainList__check--ok DKIM
              - elsif domain.dkim_status.nil?
              - else
                %li.domainList__check.domainList__check--warning{:title => domain.dkim_error}= link_to "DKIM", [:setup, organization, @server, domain]

              - if domain.mx_status == 'OK'
                %li.domainList__check.domainList__check--ok MX
              - elsif domain.mx_status.nil?
              - else
                %li.domainList__check.domainList__check--neutral-cross{:title => domain.mx_error}= link_to "MX", [:setup, organization, @server, domain]

              - if domain.return_path_status == 'OK'
                %li.domainList__check.domainList__check--ok Return Path
              - elsif domain.return_path_status.nil?
              - elsif domain.return_path_status == 'Missing'
                %li.domainList__check.domainList__check--neutral{:title => domain.return_path_error}= link_to "Return Path", [:setup, organization, @server, domain]
              - else
                %li.domainList__check.domainList__check--warning{:title => domain.return_path_error}= link_to "Return Path", [:setup, organization, @server, domain]

          %ul.domainList__properties
            - if domain.verified?
              %li.domainList__verificationTime Verified on #{domain.verified_at.to_fs(:long)}
            - else
              %li= link_to "Verify this domain", [:verify, organization, @server, domain], :class => "domainList__verificationLink"
            %li.domainList__links
              - if domain.verified?
                = link_to "DNS setup", [:setup, organization, @server, domain]
              = link_to "Delete", [organization, @server, domain], :remote => :delete, :method => :delete, :data => {:confirm => "Are you sure you wish to remove this domain?", :disable_with => "Deleting..."}, :class => 'domainList__delete'

    %p.u-center= link_to "Add new domain", [:new, organization, @server, :domain], :class => "button button--positive"

app/views/domains/new.html.haml
- if @server
  - page_title << @server.name
- page_title << "Add Domain"

- if @server
  = render 'servers/sidebar', :active_server => @server
  = render 'servers/header', :active_nav => :domains
  = render 'nav', :active_nav => :domains
- else
  .pageHeader
    %h1.pageHeader__title
      %span.pageHeader__titlePrevious
        = @organization.name
        &rarr; Domains &rarr;
      Add new domain
  = render 'organizations/nav', :active_nav => :domains

.pageContent.pageContent--compact
  = form_for [organization, @server, @domain], :remote => true do |f|
    = f.error_messages
    %fieldset.fieldSet
      .fieldSet__field
        = f.label :name, :class => 'fieldSet__label'
        .fieldSet__input= f.text_field :name, :autofocus => true, :class => 'input input--text'
      - unless current_user.admin?
        .fieldSet__field
          = f.label :verification_method, :class => 'fieldSet__label'
          .fieldSet__input
            = f.select :verification_method, Domain::VERIFICATION_METHODS, {}, :class => 'input input--select'
            .fieldSet__text
              Choose how you'd like to verify your ownership of this domain. If you choose <b>E-Mail</b> we can send you
              an email with a code whcih you'll need to enter - you can choose from a set of pre-defined addresses for
              the domain. Using <b>DNS</b> you'll need to add a TXT record on this domain using your DNS provider.

    .fieldSetSubmit
      = f.submit :class => "button button--positive js-form-submit"

app/views/domains/setup.html.haml
- if @server
  - page_title << @server.name
- page_title << @domain.name
- page_title << "DNS Setup"


- if @server
  = render 'servers/sidebar', :active_server => @server
  = render 'servers/header', :active_nav => :domains
  = render 'nav', :active_nav => :domains
- else
  .pageHeader
    %h1.pageHeader__title
      %span.pageHeader__titlePrevious
        = @organization.name
        &rarr; Domains &rarr;
      = @domain.name
  = render 'organizations/nav', :active_nav => :domains

.pageContent.pageContent--compact
  %h2.pageContent__title DNS Setup for #{@domain.name}
  %p.pageContent__intro.u-margin
    Follow the instructions below to configure SPF & DKIM records for this domain.
    We highly recommend that you do this to ensure your messages are delivered
    correctly and quickly.

  .u-margin.buttonSet
    = link_to "Check my records are correct", [:check, organization, @server, @domain], :remote => true, :method => :post, :class => 'button'
    = link_to "Back to domain list", [organization, @server, :domains], :class => 'button button--neutral'
  - if @domain.dns_checked_at
    %p.u-margin We last checked the validity of your DNS records #{distance_of_time_in_words_to_now @domain.dns_checked_at} ago.

  %h3.pageContent__subTitle SPF Record
  - if @domain.spf_status == 'OK'
    %p.pageContent__text.u-green.u-bold
      %span.label.label--green Good
      Your SPF record looks good!
  - elsif !@domain.spf_status.nil?
    %p.pageContent__text.u-orange.u-bold
      %span.label.label--orange Warning
      = @domain.spf_error

  %p.pageContent__text
    You need to add a TXT record at the apex/root of your domain (@) with the following
    content. If you already send mail from another service, you may just need to add
    <b>include:#{Postal::Config.dns.spf_include}</b> to your existing record.
  %pre.codeBlock.u-margin= @domain.spf_record

  %h3.pageContent__subTitle DKIM Record
  - if @domain.dkim_status == 'OK'
    %p.pageContent__text.u-green.u-bold
      %span.label.label--green Good
      Your DKIM record looks good!
  - elsif !@domain.dkim_status.nil?
    %p.pageContent__text.u-orange.u-bold
      %span.label.label--orange Warning
      = @domain.dkim_error

  %p.pageContent__text
    You need to add a new TXT record with the name <b>#{@domain.dkim_record_name}</b>
    with the following content.
  %pre.codeBlock.u-margin= @domain.dkim_record

  %h3.pageContent__subTitle Return Path
  - if @domain.return_path_status == 'OK'
    %p.pageContent__text.u-green.u-bold
      %span.label.label--green Good
      Your return path looks good. We'll use this when sending e-mail from this domain.
  - elsif @domain.return_path_status == 'Missing'
    %p.pageContent__text.u-grey.u-bold
      %span.label.label--grey OK
      There's no return path for this domain. This is OK but we recommend adding the record to improve deliverability and achieve DMARC alignment.
  - elsif !@domain.return_path_status.nil?
    %p.pageContent__text.u-orange.u-bold
      %span.label.label--orange Warning
      = @domain.return_path_error

  %p.pageContent__text
    This is optional but we recommend adding this to improve deliverability. You should add
    a <b>CNAME</b> record at <b>#{@domain.return_path_domain}</b> to point to the hostname below.
  %pre.codeBlock.u-margin= Postal::Config.dns.return_path_domain


  %h3.pageContent__subTitle MX Records
  - if @domain.mx_status == 'OK'
    %p.pageContent__text.u-green.u-bold
      %span.label.label--green Good
      Your MX records look like they're good to go!
  - elsif @domain.mx_status == 'Missing'
    %p.pageContent__text.u-grey.u-bold
      %span.label.label--grey OK
      None of the MX records for this domain point to us. Incoming mail won't be sent to us.
  - elsif !@domain.mx_status.nil?
    %p.pageContent__text.u-orange.u-bold
      %span.label.label--orange Warning
      = @domain.mx_error

  %p.pageContent__text
    If you wish to receive incoming e-mail for this domain, you need to add the following MX records
    to the domain. You don't have to do this and we'll only tell you if they're set up or not. Both
    records should be priority <b>10</b>.
  %pre.codeBlock.u-margin= Postal::Config.dns.mx_records.join("\n")

app/views/domains/verify.html.haml
- if @server
  - page_title << @server.name
- page_title << @domain.name
- page_title << "Verify"


- if @server
  = render 'servers/sidebar', :active_server => @server
  = render 'servers/header', :active_nav => :domains
  = render 'nav', :active_nav => :domains
- else
  .pageHeader
    %h1.pageHeader__title
      %span.pageHeader__titlePrevious
        = @organization.name
        &rarr; Domains &rarr;
      = @domain.name
  = render 'organizations/nav', :active_nav => :domains

.pageContent.pageContent--compact
  = render :partial => "verify_with_#{@domain.verification_method.underscore}"