config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Legacy API Routes
  match "/api/v1/send/message" => "legacy_api/send#message", via: [:get, :post, :patch, :put]
  match "/api/v1/send/raw" => "legacy_api/send#raw", via: [:get, :post, :patch, :put]
  match "/api/v1/messages/message" => "legacy_api/messages#message", via: [:get, :post, :patch, :put]
  match "/api/v1/messages/deliveries" => "legacy_api/messages#deliveries", via: [:get, :post, :patch, :put]

  scope "org/:org_permalink", as: "organization" do
    resources :domains, only: [:index, :new, :create, :destroy] do
      match :verify, on: :member, via: [:get, :post]
      get :setup, on: :member
      post :check, on: :member
    end
    resources :servers, except: [:index] do
      resources :domains, only: [:index, :new, :create, :destroy] do
        match :verify, on: :member, via: [:get, :post]
        get :setup, on: :member
        post :check, on: :member
      end
      resources :track_domains do
        post :toggle_ssl, on: :member
        post :check, on: :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, on: :collection
        get :outgoing, on: :collection
        get :held, on: :collection
        get :activity, on: :member
        get :plain, on: :member
        get :html, on: :member
        get :html_raw, on: :member
        get :attachments, on: :member
        get :headers, on: :member
        get :attachment, on: :member
        get :download, on: :member
        get :spam_checks, on: :member
        post :retry, on: :member
        post :cancel_hold, on: :member
        get :suppressions, on: :collection
        delete :remove_from_queue, on: :member
        get :deliveries, on: :member
      end
      resources :webhooks do
        get :history, on: :collection
        get "history/:uuid", on: :collection, action: "history_request", as: "history_request"
      end
      get :limits, on: :member
      get :retention, on: :member
      get :queue, on: :member
      get :spam, on: :member
      get :delete, on: :member
      get "help/outgoing" => "help#outgoing"
      get "help/incoming" => "help#incoming"
      get :advanced, on: :member
      post :suspend, on: :member
      post :unsuspend, on: :member
    end

    resources :ip_pool_rules
    resources :ip_pools, controller: "organization_ip_pools" do
      put :assignments, on: :collection
    end
    root "servers#index"
    get "settings" => "organizations#edit"
    patch "settings" => "organizations#update"
    get "delete" => "organizations#delete"
    delete "delete" => "organizations#destroy"
  end

  resources :organizations, except: [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get "settings" => "user#edit"
  patch "settings" => "user#update"
  post "persist" => "sessions#persist"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  match "login/reset" => "sessions#begin_password_reset", :via => [:get, :post]
  match "login/reset/:token" => "sessions#finish_password_reset", :via => [:get, :post]

  if Postal::Config.oidc.enabled?
    get "auth/oidc/callback", to: "sessions#create_from_oidc"
  end

  get ".well-known/jwks.json" => "well_known#jwks"

  get "ip" => "sessions#ip"

  root "organizations#index"
end

app/models/organization.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: organizations
#
#  id                :integer          not null, primary key
#  uuid              :string(255)
#  name              :string(255)
#  permalink         :string(255)
#  time_zone         :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  ip_pool_id        :integer
#  owner_id          :integer
#  deleted_at        :datetime
#  suspended_at      :datetime
#  suspension_reason :string(255)
#
# Indexes
#
#  index_organizations_on_permalink  (permalink)
#  index_organizations_on_uuid       (uuid)
#

class Organization < ApplicationRecord

  RESERVED_PERMALINKS = %w[new edit remove delete destroy admin mail org server].freeze

  INITIAL_QUOTA = 10
  INITIAL_SUPER_QUOTA = 10_000
  include HasUUID
  include HasSoftDestroy

  validates :name, presence: true
  validates :permalink, presence: true, format: { with: /\A[a-z0-9-]*\z/ }, uniqueness: { case_sensitive: false }, exclusion: { in: RESERVED_PERMALINKS }
  validates :time_zone, presence: true

  default_value :time_zone, -> { "UTC" }
  default_value :permalink, -> { Organization.find_unique_permalink(name) if name }

  belongs_to :owner, class_name: "User"
  has_many :organization_users, dependent: :destroy
  has_many :users, through: :organization_users, source_type: "User"
  has_many :user_invites, through: :organization_users, source_type: "UserInvite", source: :user
  has_many :servers, dependent: :destroy
  has_many :domains, as: :owner, dependent: :destroy
  has_many :organization_ip_pools, dependent: :destroy
  has_many :ip_pools, through: :organization_ip_pools
  has_many :ip_pool_rules, dependent: :destroy, as: :owner

  after_create do
    if IPPool.default
      ip_pools << IPPool.default
    end
  end

  def status
    if suspended?
      "Suspended"
    else
      "Active"
    end
  end

  def to_param
    permalink
  end

  def suspended?
    suspended_at.present?
  end

  def user_assignment(user)
    @user_assignments ||= {}
    @user_assignments[user.id] ||= organization_users.where(user: user).first
  end

  def make_owner(new_owner)
    user_assignment(new_owner).update(admin: true, all_servers: true)
    update(owner: new_owner)
  end

  # This is an array of addresses that should receive notifications for this organization
  def notification_addresses
    users.map(&:email_tag)
  end

  def self.find_unique_permalink(name)
    loop.each_with_index do |_, i|
      i += 1
      proposal = name.parameterize
      proposal += "-#{i}" if i > 1
      unless where(permalink: proposal).exists?
        return proposal
      end
    end
  end

  def self.[](id)
    if id.is_a?(String)
      where(permalink: id).first
    else
      where(id: id.to_i).first
    end
  end

end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController

  before_action :admin_required, only: [:new, :create, :delete, :destroy]

  def index
    if current_user.admin?
      @organizations = Organization.present.order(:name).to_a
    else
      @organizations = current_user.organizations.present.order(:name).to_a
      if @organizations.size == 1 && params[:nrd].nil?
        redirect_to organization_root_path(@organizations.first)
      end
    end
  end

  def new
    @organization = Organization.new
  end

  def edit
    @organization_obj = current_user.organizations_scope.find(organization.id)
  end

  def create
    @organization = Organization.new(params.require(:organization).permit(:name, :permalink))
    @organization.owner = current_user
    if @organization.save
      redirect_to_with_json organization_root_path(@organization)
    else
      render_form_errors "new", @organization
    end
  end

  def update
    @organization_obj = current_user.organizations_scope.find(organization.id)
    if @organization_obj.update(params.require(:organization).permit(:name, :time_zone))
      redirect_to_with_json organization_settings_path(@organization_obj), notice: "Settings for #{@organization_obj.name} have been saved successfully."
    else
      render_form_errors "edit", @organization_obj
    end
  end

  def destroy
    if params[:confirm_text].blank? || params[:confirm_text].downcase.strip != organization.name.downcase.strip
      respond_to do |wants|
        alert_text = "The text you entered does not match the organization name. Please check and try again."
        wants.html { redirect_to organization_delete_path(@organization), alert: alert_text }
        wants.json { render json: { alert: alert_text } }
      end
      return
    end

    organization.soft_destroy
    redirect_to_with_json root_path(nrd: 1), notice: "#{@organization.name} has been removed successfully."
  end

  private

  def organization
    return unless [:edit, :update, :delete, :destroy].include?(action_name.to_sym)

    @organization ||= params[:org_permalink] ? current_user.organizations_scope.find_by_permalink!(params[:org_permalink]) : nil
  end
  helper_method :organization

end

app/views/organizations/_nav.html.haml
.navBar
  %ul
    %li.navBar__item= link_to "Mail Servers", organization_root_path(organization), :class => ['navBar__link', active_nav == :servers ? 'is-active' : '']
    %li.navBar__item= link_to "Domains", organization_domains_path(organization), :class => ['navBar__link', active_nav == :domains ? 'is-active' : '']
    %li.navBar__item= link_to "Settings", organization_settings_path(organization), :class => ['navBar__link', active_nav == :settings ? 'is-active' : '']
    - if Postal.ip_pools?
      %li.navBar__item= link_to "IPs", organization_ip_pools_path(organization), :class => ['navBar__link', active_nav == :ips ? 'is-active' : '']
    - if current_user.admin?
      %li.navBar__item= link_to "Delete Organization", organization_delete_path(organization), :class => ['navBar__link', active_nav == :delete ? 'is-active' : '']

app/views/organizations/delete.html.haml
- page_title << organization.name
- page_title << "Delete"
.pageHeader
  %h1.pageHeader__title
    %span.pageHeader__titlePrevious
      = organization.name
      &rarr;
    Delete organization
= render 'nav', :active_nav => :delete
.pageContent.pageContent--compact
  %h2.pageContent__intro.u-margin
    If you no longer need this organization you can delete it. When you delete an organization
    all its mail servers & data will be deleted from our systems.
  .dangerZone
    %p.pageContent__text.u-margin
      To continue to delete this organization, please enter the name of the organization in the field below and press
      continue. <b class='u-red'>There will be no other confirmations.</b>
    = form_tag [organization, :delete], :method => :delete, :remote => true do
      = hidden_field_tag 'return_to', params[:return_to]
      %p.u-margin
        = text_field_tag "confirm_text", '', :class => 'input input--text input--danger'
      .buttonSet.u-center
        = submit_tag "Delete this organization, mail servers and all messages", :class => 'button button--danger js-form-submit'

app/views/organizations/edit.html.haml
- page_title << @organization.name
- page_title << "Organization Settings"
.pageHeader
  %h1.pageHeader__title
    %span.pageHeader__titlePrevious
      = @organization.name
      &rarr;
    Settings

= render 'nav', :active_nav => :settings

.pageContent.pageContent--compact
  = form_for @organization_obj, :url => organization_settings_path(@organization_obj), :remote => true do |f|
    = f.error_messages
    %fieldset.fieldSet
      .fieldSet__field
        = f.label :name, :class => 'fieldSet__label'
        .fieldSet__input= f.text_field :name, :autofocus => true, :class => 'input input--text'
      .fieldSet__field
        = f.label :time_zone, :class => 'fieldSet__label'
        .fieldSet__input
          = f.time_zone_select :time_zone, [], {}, :class => 'input input--select'
          %p.fieldSet__text
            Choose the time zone that your organization exists within. This is used when displaying times in places
            where there isn't a logged in user to provide their own time zone.

    %p.fieldSetSubmit.buttonSet
      = f.submit "Save Settings", :class => 'button button--positive js-form-submit'

app/views/organizations/index.html.haml
- page_title << "Welcome"

.pageHeader
  %h1.pageHeader__title Welcome to Postal, #{current_user.first_name}

.pageContent.pageContent--compact

  - if @organizations.empty?
    .noData.noData--clean
      %p.noData__title There are no organizations.
      - if current_user.admin?
        %p.noData__text
          You need an organization otherwise you can't do much here. Hit
          the button below to create the first organization.
        %p.noData__button= link_to "Create the first organization", :new_organization, :class => 'button button--positive'
      - else
        %p.noData__text
          You don't have access to any organizations yet. Ask your administrator to invite
          you to some organizations.
  - else
    %p.pageContent__intro.u-margin
      Organizations are entities which are able to deploy mail servers.
      Choose an existing organization from the list opposite or use the button below
      to create a new one.

    %ul.largeList.u-margin
      - for organization in @organizations
        %li.largeList__item
          = link_to organization_root_path(organization), :class => 'largeList__link' do
            = organization.name

    - if current_user.admin?
      %p.u-center= link_to "Start another organization", :new_organization, :class => 'button button--positive'

app/views/organizations/new.html.haml
- page_title << "Create a new organization"
.pageHeader
  %h1.pageHeader__title Create a new organization
.pageContent.pageContent--compact
  %p.pageContent__intro.u-margin
    If you're starting a new organization you can do so by completing this form. You'll be able
    to invite new users & create mail servers as soon as it has been created.
  = form_for @organization, :remote => true do |f|
    = f.error_messages
    %fieldset.fieldSet
      .fieldSet__field
        = f.label :name, :class => 'fieldSet__label'
        .fieldSet__input= f.text_field :name, :autofocus => true, :class => 'input input--text'
      .fieldSet__field
        = f.label :permalink, :class => 'fieldSet__label'
        .fieldSet__input
          = f.text_field :permalink, :class => 'input input--text', :placeholder => "Automatically generated"
          %p.fieldSet__text
            This is a short name which is used in usernames and the API to identify your organization.
            It should only contain letters, numbers & hyphens.

    .fieldSetSubmit.buttonSet
      = f.submit "Create organization", :class => 'button button--positive js-form-submit'
      .fieldSetSubmit__delete
        = link_to "Back to homepage", root_path, :class => 'button button--neutral'